WIP: Adds first 3 models
USGS-WiM/stnservices-django pull request #9
Opened 2022-02-25 23:00 UTC by lprivette

2022-02-28 19:28 UTC, aaronstephenson requested changes
Overall this is a great first pass! I made a bunch of comments to give you my perspective based on what I've encountered on other projects, but feel free to ignore any or all of them. :)

Really the only "must do" change is the model name for 'Approval'.

2022-02-28 19:28 UTC, aaronstephenson commented on stnservices/quickstart/models.py
> +    agency_id = models.IntegerField(null=True, help_text='An integer value of the agency id for this agency')
Every primary key field can be defined implicitly, unless you have a reason to override the default (in this case, I'm guessing the current STN Services have a field with this name, so we need to continue with it?): https://docs.djangoproject.com/en/4.0/topics/db/models/#automatic-primary-key-fields

2022-02-28 19:28 UTC, aaronstephenson commented on stnservices/quickstart/models.py
> +    agency_name = models.CharField(max_length=128, blank=True, default='', help_text='An alphanumeric value of the name of this agency')
Related to the `id` field, I have found that the common model 'name' field can be defined as just plain `name`, because the 'thing' or 'type' that it is naming (in this case, agency name) is implicit in the class name. For example, when accessing this field in Python you would use dot notation, `Agency.name`, so to me `Agency.agency_name` is somewhat redundant. However, I am also guilty of going the other way on this; my earliest project, Merlin, has the name fields defined as the class name, e.g. `Constituent.constituent`, and in retrospect I cringe at that.

But maybe this is another case, like `id`, where the names are already established in the current STN Services?

2022-02-28 19:28 UTC, aaronstephenson commented on stnservices/quickstart/models.py
> +        ordering = ['id']
This is perfectly OK to do, but I would recommend against it. If at any point you need to do complicated queries against this model, the model's base `ordering` setting can interfere with the SQL and produce unexpected results, or more likely just prevent the query from executing and returning an error (this has happened to me a lot). Defining it in the model also incurs a (variable, maybe negligible, maybe noticeable) performance hit on the DB.

IMHO, the best place to apply ordering is in the serializer or the view, when returning a queryset. It's as easy as
```
queryset = Agency.objects.all().order_by('id')
```

2022-02-28 19:28 UTC, aaronstephenson commented on stnservices/quickstart/models.py
> +class Agencies(models.Model):
Should this be `Approval`?

2022-02-28 19:28 UTC, aaronstephenson commented on stnservices/quickstart/models.py
> +    Appoval
Missing the 'r'.

2022-02-28 19:28 UTC, aaronstephenson commented on stnservices/quickstart/models.py
> +        verbose_name_plural = "approvals"
Django automatically makes models plural by appending an 's', so you really only need to set this property if a simple 's' is incorrect, e.g. 'agencies' vs' the default 'agencys'.

2022-02-28 19:32 UTC, aaronstephenson commented on stnservices/quickstart/models.py
> +    agency_name = models.CharField(max_length=128, blank=True, default='', help_text='An alphanumeric value of the name of this agency')
Also, these 'name' fields (if they will all have the same name in each model) are a great candidate for an Abstract Base Class: https://docs.djangoproject.com/en/4.0/topics/db/models/#abstract-base-classes. I use them extensively in my projects (you can even nest them!); here's an example from WHISPers: https://github.com/USGS-WiM/whispersservices/blob/master/whispersapi/models.py#L232

2022-02-28 19:34 UTC, aaronstephenson commented
Oh, I would also recommend renaming this 'app' from 'quickstart' to something like 'stnapi'.

2022-02-28 22:34 UTC, lprivette commented on stnservices/quickstart/models.py
> +    agency_id = models.IntegerField(null=True, help_text='An integer value of the agency id for this agency')
Yes they have a field with this name, but it makes sense to me to leave it to be defined implicitly. So to make sure I'm following correctly-- in the models I would remove the `blah_id` line and when we migrate each table would have it's default `id` field?

2022-02-28 22:38 UTC, lprivette commented on stnservices/quickstart/models.py
> +    agency_name = models.CharField(max_length=128, blank=True, default='', help_text='An alphanumeric value of the name of this agency')
I totally agree with this, it does seem redundant.  In current stn services yes they are established that way, but that's not forcing us to continue this pattern right? I'm ok with updating the client to account for this when we go live with django servcies

2022-02-28 22:39 UTC, aaronstephenson commented on stnservices/quickstart/models.py
> +    agency_id = models.IntegerField(null=True, help_text='An integer value of the agency id for this agency')
If you go with the implicit id, the field will literally be `id`, which is good practice by may not be what you want if current users expect `agency_id`.

2022-02-28 22:47 UTC, lprivette commented on stnservices/quickstart/models.py
> +    agency_id = models.IntegerField(null=True, help_text='An integer value of the agency id for this agency')
gr. I want to do it right and not carry over outdated practices. FEV and STN are the heaviest users and I don't think FEV even uses any agency endpoint. I'm not even aware of anyone else using it but it's possible someone is.

2022-02-28 22:51 UTC, lprivette commented on stnservices/quickstart/models.py
> +class Agencies(models.Model):
resolved in https://github.com/USGS-WiM/stnservices-django/commit/27b15285fc6f78b9c10f10f2dc8e3f3188af5711

2022-02-28 22:52 UTC, lprivette commented on stnservices/quickstart/models.py
> +        ordering = ['id']
resolved in https://github.com/USGS-WiM/stnservices-django/commit/27b15285fc6f78b9c10f10f2dc8e3f3188af5711

2022-02-28 23:40 UTC, lprivette commented on stnservices/quickstart/models.py
> +    agency_id = models.IntegerField(null=True, help_text='An integer value of the agency id for this agency')
fixed in https://github.com/USGS-WiM/stnservices-django/commit/9ba08f05ebef123379360b365e4018c9c217d415

2022-02-28 23:40 UTC, lprivette commented on stnservices/quickstart/models.py
> +    agency_name = models.CharField(max_length=128, blank=True, default='', help_text='An alphanumeric value of the name of this agency')
fixed in https://github.com/USGS-WiM/stnservices-django/commit/9ba08f05ebef123379360b365e4018c9c217d415

2022-02-28 23:40 UTC, lprivette commented on stnservices/quickstart/models.py
> +    Appoval
fixed in https://github.com/USGS-WiM/stnservices-django/commit/9ba08f05ebef123379360b365e4018c9c217d415

2022-02-28 23:41 UTC, lprivette commented on stnservices/quickstart/models.py
> +        verbose_name_plural = "approvals"
Ok I think I understand so removed the `verbose_name_plural` lines for the Contact and Approval, but left it for Agency : https://github.com/USGS-WiM/stnservices-django/commit/9ba08f05ebef123379360b365e4018c9c217d415

2022-03-01 19:14 UTC, aaronstephenson approved these changes
Looks good!

2022-03-01 19:14 UTC, merged